title: Kyle Woolford
identity: >-
  Tech enthusiast playing with the latest tools and enjoying the technology explosion
description: >-
  Personal site for fun
author: Kyle Woolford
email: kyle.woolford@gmail.com
url: "https://kwoolford.github.io"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: /:categories/:title/

sass:
  style: compressed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
  - .bundle/

show_excerpts: true
